language: python

python: "3.4"

env:
  global:
    - EDGI_ZOOM_DELETE_AFTER_UPLOAD=1
    # EDGI_ZOOM_API_KEY
    - secure: "7HMDIcFtyfi0gUJT3KDDgAZy0Yxh0QqDVw8Th4gBpghhHQiLMpbrjdXPxSTDDDUYb8+pSwM+NDlv7g7XSBllBzcAJSrW4S42Pgrulzu7qFWrKV2uSC8zNCnwA4b20Kwp/TmTW9PtOXSeBdb4l1xsfFroWJvcSsbIITM5nW2LQTqTQvk0O5yBOp6XjzWLvjcZGCoI9QUhSi8UKF0WQn2OsKeLy/LMuQbvE27QBVLiLWAuMe2TcA7/yArtQqbkKqACR7w5LCz39EsCT6nfe6Ap9ZZIv6kPUNWV6XY+IRvxAOU0pze+rIkpgAZHeZ5Jeij63J82S8m06YsOA43O75h7AiKTeCO4pLz2nG47LWNPgpMr5SnrjWW85jnCO8ZNfeg1wL3VzfPtFgRTByn3c4L+1XWmxWuG8FSkjdLZpH1lt1niTjBIIKn8TKPMmiyEfumLLaAQwyP/x3qrpaklTHCHLxeirO0ZDo6BdCTlBIl0xg2TJgn9PaoEi8yTmFVZIRPek+BbcLKE2pmcsCwDWoEUIxEH7KzgA1ygZ/N9ljz3b4RZgLpFTzWmHUurQZTA5fDuFroySiZjgYU8s1faVHNBA1+yPVwcWAxYlv5kocNHVeTtYPTXUUP1BDswoPgAOF4ytBs8D+g19eJv55IB6UUnwnJOVWLonD9wqeHWAXpqBIs="
    # EDGI_ZOOM_API_SECRET
    - secure: "lkDHQPXGN5RUd2CuglIEmlhbaUJwsayDZeSJyC16fgmfQfRE+hg67uY4ARRayHoc3Z8m6v6BNBVp947ZDCvKQ1eecSiMnfR6iSg0RWOsLAXVm2PCVzGYkVkV6hfydG7oqPwFyvwwc48EDG9wmky3eSGv7iMvtatecLt9Ta5raWRHeNCNpGyumcMOEGXVjwNcgcazVnGSw7YS0sX4tgySBDq6TAPWhEeWI0kN5C2LRyIZx0NWE4S9JuJQ7X17MGi9nus43yQ9dT642GsiLXSskCFdqpbVp7KzybIRUJznDfOCe2Ijmah6ohCK1cgi3AXmUjUIFFSp5eSQlLGUb/3JWCsoTNVmbUnARE49/FFrJpL/7YK0EZoo2WUhN/m2tbkrY0KhPuPpkS0Mc5oe5Et1QUzg4b2AGqeiE5iZznrjP8rlC3rizvssqw3j0d6S+DkG4vDKMaRpHW6J+pPG9KTwCpyEn11h28eftDz5MblHeHCiKCmYr6xvgD6K+sbNW/1mnz/YE7WTb43vx20Ca9IiHriXaxeS7Y8lbUwC+tJa/YIvVsUKYWN2K3TS9b3s37ihHTtu3G9ah1eaZEO3cQwNvsg6ASmmnyufkqAb0G8OkgiZXP/b9NXI7bhQ/9f5bqHA9dPuu7/Obuj/PXpAbg74vEIvF1MeTbTa4DVNEvfe5IE="

before_install:
  - openssl aes-256-cbc -k "$EDGI_ZOOM_API_SECRET" -in client_secret.json.enc -out client_secret.json -d
  - openssl aes-256-cbc -k "$EDGI_ZOOM_API_SECRET" -in .youtube-upload-credentials.json.enc -out .youtube-upload-credentials.json -d

script:
  - python scripts/upload_zoom_recordings.py
