language: python

python: "3.4"

env:
  global:
    - EDGI_ZOOM_DELETE_AFTER_UPLOAD=1
    # EDGI_ZOOM_API_KEY
    - secure: "IKQ6Tpvn77qlsScbF6vhR7DnMg88uHi0kgMVvjQgYy/lQlwpOA1FNZ4TjNh1FKfgAhWGQ78i+pp/0Gkbu8MFOKbAJD+6a/OADf2k7PVlZODjqfMo1yQKbGrl3AL+rYtTh8euQ4Dkvv6oLVaPah/AVMYEVmV0PcVeyeda2YAjn9RHmSf6zElRskM4WJ95kJZuPFYT1T8Ro9AgWsln9dGketmyOnic1jMHZA2il18rXizemfqiGCziR/RvJEKSSHC7lCpOKxYYV7KGMXhcnj+7wi4Q/83tsglr56P9zLS3aD+3cGpzgz+b1X1gIQvcpP9Zc9zDfTnVNvZdoISJN6+NVYEIidgkghSq1/vnKwLuN8Pl+vm46Qsjf7NEY52WCWRQoq+BP7w3Z8e5rnZra1fmlbe5g+cxPBVghFWRVKG+gyZ53RUmWBb8hSGxX0R8yPfcAv5qZW+CZDYxp3Hv9fwhrgmFt+9Fs6USkcLEoZ2FYIRiAqk6BsjAlSB7H+2DHfqCoVzWrALaQ6YfTvXMigEzfil4fTjtl99WaLAhKpqN2esZcmu+joVwQ8cR3DWd5WV7jQCKfhP9csvzNKNJD7Lv0nxpSaY7YkLxbstcVXZJbhpEJA5boWYiin5KLxMmrpNUTDHhoPh3JSrlmtcsUBbcw9tJbEcYit5xl1wiPAJsJ/4="
    # EDGI_ZOOM_API_SECRET
    - secure: "Qb7s96xQw1S3n6uwCz4+TkkumiNtYJ4N3JRlNXvU+r+97bB6dDVeffuCxvrlAlpfCCkNeZsPTG63xwV97QM5nlOEHYeKlPC5VP2jeLvOgrKO91RkMrdP3o7PcZ3m2toowWuDamvzUxaFn6eq8foMyY/qBIBrSeX5Ve7n3jGVp6SORb4/KUU8+zG2fRd+zEQyE+qdLllgigC2pGEGUZHJ5jMPfYG4VM1H6/pAPwXQ78fyGLXt3k+VYAY5Z/Pg59Byqkdg8sP3Rd3AjpLza0X7Ut/xmiNhKoP4KKEf4uCl1UTtyAmLIy8Pbbf9EQP3+UKoliCMNYCXdp2BvO5Ayy5Bdkiebr+aObG6qRrk0k2tKSi/x793wTzYLG3Obo2XRsuSq0NruQLq+iBoDPabCCsC00lro8dYzIFMfbpNf+71wzQ4Gv+OOj+RGH+aimwSjyDCSLDVo0zjkuESaCmJ95GkvJBs7KmFxR+I8fOMx0DAcYzcXv0J4gkUytmAIqMG+YKHBIxUc1Gx263HahNm+ZftSSxcPIXdHT7IHN3Lv47iSdIpxDjHoFeXx99RZ18HgUvdSDnbY1G81DqAlYQFunqDOCs3Bipj76G8Y8b0kI4E2fp88NDwQegXe3KKiJSV5SKPtQ3p5QA0sCfSKN1NiTMdYcXdmDqqhkSH/Za11vRTrBM="

before_install:
  - openssl aes-256-cbc -k "$EDGI_ZOOM_API_SECRET" -in client_secret.json.enc -out client_secret.json -d
  - openssl aes-256-cbc -k "$EDGI_ZOOM_API_SECRET" -in .youtube-upload-credentials.json.enc -out .youtube-upload-credentials.json -d

script:
  - python scripts/upload_zoom_recordings.py

branches:
  only:
    - travis-cron
